config/routes.rb
Rails.application.routes.draw do
  # Full CRUD
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :recipe_cards, only: [:index, :create, :update, :destroy] # show is through :recipes
  resources :pantry_items, only: [:index, :create, :update, :destroy] # show is through :ingredients


  # Just Read
  resources :recipes, only: [:index, :show, :update]
  resources :ingredients, only: [:index, :show]

  # Sessions
  get "/signup", to: "users#new", as: "signup"
  get "/signin", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  root to: "static#index"

  post "/pantry_items/groceries", to: "pantry_items#groceries", as: "pantry_groceries"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :recipe_cards
  has_many :users, through: :recipe_cards
  has_many :instructions

  def to_recipe_ingredient(ingredient_id)
    RecipeIngredient.find_by(recipe_id: self.id, ingredient_id: ingredient_id)
  end

  def to_recipe_card(user_id)
    RecipeCard.find_by(user_id: user_id, recipe_id: self.id)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
    @user = current_user
    @recipe_card = RecipeCard.new(user_id: @user.id)

    if params[:recipe_name]
      @recipes = @recipes.select {|recipe| recipe.name.downcase.include?(params[:recipe_name].downcase)}
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @instructions = @recipe.instructions
    @recipe_ingredients = @recipe.recipe_ingredients
    @user = current_user
    @recipe_card = RecipeCard.find_or_initialize_by(recipe_id: @recipe.id, user_id: @user.id)
  end

  private
    def recipe_params
      params.require(:recipe).permit(:name, :yield, :total_cooking_time)
    end


end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<%= form_tag recipes_path, method: :get do %>
  <b><%= label_tag :recipe_name, "Search by recipe name:" %></b>
  <br>
  <%= search_field_tag :recipe_name %>
  <%= submit_tag 'Search' %>
<% end %>

<% @recipes.each do |recipe| %>
  <div class="container">
    <div style ='float: left; padding: 5px;'>
      <%= link_to recipe.name.titleize, recipe_path(recipe)%>
    </div>
      <% if !recipe.to_recipe_card(@user.id) %>
        <div style ='float: left; padding: 5px;'>
          <%= form_for @recipe_card do |f|%>
          <%= f.number_field :user_id, type: :hidden %>
          <%= f.number_field :recipe_id, value: "#{recipe.id}", type: :hidden %>
          <%= text_field_tag :source, nil, value: "recipes_path", type: :hidden%>
          <%= f.submit "Add to Cookbook"%>
          <% end %>
        </div>
      <% else %>
      <div style ='float: left; padding: 5px;'>
        <%= form_for recipe.to_recipe_card(@user.id), method: :delete do |f|%>
        <%= text_field_tag :source, nil, value: "recipes_path", type: :hidden%>
        <%= f.submit "Remove from Cookbook" %>
        <% end %>
      </div>
      <% end %>
    </div>



  <% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name%></h1>
<h3><%= "Yield: #{@recipe.yield}"  %></h3>
<h3><%= "Total Cooking Time: #{@recipe.total_cooking_time}"  %></h3>
<br>
<div class="container">
<% if @recipe_card.id %>
<div style ='float: left; padding: 5px;'>
  <% if @recipe_card.favorite %>
    <%= form_for @recipe_card do |f|%>
    <%= f.number_field :recipe_id, type: :hidden%>
    <%= f.number_field :user_id, type: :hidden%>
    <%= f.text_field :favorite, value: false, type: :hidden%>
    <%= f.text_field :to_be_cooked, type: :hidden%>
    <%= text_field_tag :source, nil, value: "recipe_path(@recipe)", type: :hidden%>
    <%= f.submit "Remove from Favorites" %>
    <% end %>
  <% else %>
    <%= form_for @recipe_card do |f|%>
    <%= f.number_field :recipe_id, type: :hidden%>
    <%= f.number_field :user_id, type: :hidden%>
    <%= f.text_field :favorite, value: true, type: :hidden%>
    <%= f.text_field :to_be_cooked, type: :hidden%>
    <%= text_field_tag :source, nil, value: "recipe_path(@recipe)", type: :hidden%>
    <%= f.submit "Add to Favorites" %>
    <% end %>
  <% end %>
</div>
<div style ='float: left; padding: 5px;'>
  <% if @recipe_card.to_be_cooked %>
    <%= form_for @recipe_card do |f|%>
    <%= f.number_field :recipe_id, type: :hidden%>
    <%= f.number_field :user_id, type: :hidden%>
    <%= f.text_field :favorite, type: :hidden%>
    <%= f.text_field :to_be_cooked, value: false, type: :hidden%>
    <%= text_field_tag :source, nil, value: "recipe_path(@recipe)", type: :hidden%>
    <%= f.submit "Remove from Meal Calendar" %>
    <% end %>
  <% else %>
    <%= form_for @recipe_card do |f|%>
    <%= f.number_field :recipe_id, type: :hidden%>
    <%= f.number_field :user_id, type: :hidden%>
    <%= f.text_field :favorite, type: :hidden%>
    <%= f.text_field :to_be_cooked, value: true, type: :hidden%>
    <%= text_field_tag :source, nil, value: "recipe_path(@recipe)", type: :hidden%>
    <%= f.submit "Add to Meal Calendar" %>
    <% end %>
  <% end %>
  </div>
  <div style ='float: left; padding: 5px;'>
    <%= form_for @recipe_card, method: :delete do |f|%>
    <%= text_field_tag :source, nil, value: "recipe_path(@recipe)", type: :hidden%>
    <%= f.submit "Remove from Cookbook" %>
    <% end %>
  </div>
  
  <% else %>
  <div style ='float: left; padding: 5px;'>
    <%= form_for @recipe_card do |f|%>
    <%= f.number_field :recipe_id, type: :hidden%>
    <%= f.number_field :user_id, type: :hidden%>
    <%= f.text_field :favorite, type: :hidden%>
    <%= f.text_field :to_be_cooked, type: :hidden%>
    <%= text_field_tag :source, nil, value: "recipe_path(@recipe)", type: :hidden%>
    <%= f.submit "Add to Cookbook" %>
    <% end %>
  </div>
  <% end %>
</div>
<br>
<% if @user.cookable?(@recipe) %>
  <p>All ingredients currently in stock</p>
<% else %>
  <p>You do not currently have all necessary ingredients to cook this recipe.</p>
<% end %>
<h3>Ingredients: </h3>
<ul><% @recipe_ingredients.each do |recipe_ingredient| %>
  <li><%= "#{recipe_ingredient.quantity_with_measurement} of "%><%=link_to recipe_ingredient.ingredient.name.split.map(&:capitalize).join(' '), ingredient_path(recipe_ingredient.ingredient)%><%=recipe_ingredient.extra_instructions%> </li>
  <%end%>
</ul>


<h3>Directions:</h3>
<ol>
<% @instructions.each do |instruction|  %>
  <li><%= instruction.instruction_text %></li>
<%end%>
<ol>