config/routes.rb
Rails.application.routes.draw do
  # Full CRUD
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :recipe_cards, only: [:index, :create, :update, :destroy] # show is through :recipes
  resources :pantry_items, only: [:index, :create, :update, :destroy] # show is through :ingredients


  # Just Read
  resources :recipes, only: [:index, :show, :update]
  resources :ingredients, only: [:index, :show]

  # Sessions
  get "/signup", to: "users#new", as: "signup"
  get "/signin", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  root to: "static#index"

  post "/pantry_items/groceries", to: "pantry_items#groceries", as: "pantry_groceries"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipe_cards, dependent: :destroy
  has_many :recipes, through: :recipe_cards
  has_many :pantry_items,  dependent: :destroy
  has_many :ingredients, through: :pantry_items
  has_secure_password
  validates_confirmation_of :password_digest



  def ingredients_in_stock
    result = self.ingredients.select {|ingredient| ingredient.to_pantry_item(self.id).in_stock}
    result ||= []
  end

  def ingredients_out_of_stock
    result = self.ingredients.reject {|ingredient| ingredient.to_pantry_item(self.id).in_stock}
    result ||= []
  end

  def recipes_to_be_cooked # returns array of recipes to be cooked by user. uses "to_be_cooked" boolean attribute on recipecards
    result = self.recipes.select {|recipe| recipe.to_recipe_card(self.id).to_be_cooked}.uniq
    result ||= []
  end

  def ingredients_needed_for_recipes_to_be_cooked
    result = self.recipes_to_be_cooked.map {|recipe| recipe.ingredients}.flatten.uniq
    result ||= []
  end

  def grocery_list # returns array of ingredients to pick up. includes ingredients from "to_be_cooked" not in pantry, as well as ingredients in pantry marked as "out of stock"
    # uses "to_be_cooked" to parse through recipes on deck. cross references each recipe's ingredients and amounts with pantry's ingredients and amounts
    result = (self.ingredients_needed_for_recipes_to_be_cooked - self.ingredients_in_stock) | self.ingredients_out_of_stock
    result ||= []
  end

  def cookable?(recipe) #cross references recipe's list of ingredients with user's pantry items
    recipe.ingredients.all? {|ingredient| self.ingredients_in_stock.include?(ingredient)}
  end

  def ingredients_needed_for_recipe(recipe_id)
    recipe = Recipe.find(recipe_id)
    result = recipe.ingredients.reject {|ingredient| self.ingredients_in_stock.include?(ingredient)}
    result ||= []
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def show
    @user = current_user
    @recipes_to_be_cooked = @user.recipes_to_be_cooked
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path
  end


  private
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Settings</h1>

<h2>Edit:</h2>
<%= render "form" %>

<br>

<h2>Delete Account</h2>
<%= button_to "Delete account", user_path(@user), method: :delete%>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form" %>

app/views/users/show.html.erb
<h1>Welcome, <%=@user.username%>!</h1>


<% if @recipes_to_be_cooked == [] %>
  <h3>There are currently no recipes on deck.</h3>
     <p>Add recipes to Meal Calendar to form a meal plan.</p>
  <%= button_to "View Cookbook", recipe_cards_path, method: :get %>
<% else %>
  <h3>Recipes On Deck:</h3>

  <% @recipes_to_be_cooked.each do |recipe| %>
    <%= link_to recipe.name, recipe_path(recipe) %>
    <div class="container">
    <div style ='float: left; padding: 5px;'>
      <% if @user.cookable?(recipe) %>
        <%= form_for (recipe.to_recipe_card(@user.id)) do |f|%>
        <%= f.number_field :user_id, type: :hidden %>
        <%= f.number_field :recipe_id, type: :hidden %>
        <%= f.number_field :favorite, type: :hidden %>
        <%= f.text_field :to_be_cooked, value: false, type: :hidden %>
        <%= text_field_tag :source, nil, value: "user_path(current_user)", type: :hidden%>
        <%= f.submit "Remove From Meal Calendar"%>
        <% end %>
      <% else %>
          You are out of:
        <ul><% @user.ingredients_needed_for_recipe(recipe.id).each do |ingredient| %>
           <li><%= link_to ingredient.name.titleize, ingredient_path(ingredient) %></li>
       <% end %>
       </ul>
       <%= form_tag "/pantry_items/groceries" do %>
       <%= text_field_tag :source, nil, value: "user_path(current_user)", type: :hidden%>
       <%= text_field_tag :recipe_id, nil, value: "#{recipe.id}", type: :hidden%>
       <%= submit_tag "Buy All Ingredients For This Recipe" %>
       <% end %>
      <% end %>
    </div>
    </div>

    <% end %>
<% end %>

<br>
<br>
<%= button_to "Settings", edit_user_path(@user), method: :get%>