config/routes.rb
Rails.application.routes.draw do
  # Full CRUD
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :recipe_cards, only: [:index, :create, :update, :destroy] # show is through :recipes
  resources :pantry_items, only: [:index, :create, :update, :destroy] # show is through :ingredients


  # Just Read
  resources :recipes, only: [:index, :show, :update]
  resources :ingredients, only: [:index, :show]

  # Sessions
  get "/signup", to: "users#new", as: "signup"
  get "/signin", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  root to: "static#index"

  post "/pantry_items/groceries", to: "pantry_items#groceries", as: "pantry_groceries"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  has_many :pantry_items
  has_many :users, through: :pantry_items

  def units_of_measurement
    self.recipe_ingredients.map {|r_i| r_i.unit_of_measurement}.uniq
  end

  def to_recipe_ingredient(recipe_id)
    RecipeIngredient.find_by(recipe_id: recipe_id, ingredient_id: self.id)
  end

  def to_pantry_item(user_id)
    PantryItem.find_by(user_id: user_id, ingredient_id: self.id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients_in_stock = current_user.ingredients_in_stock
    @grocery_list = current_user.grocery_list
    @other_ingredients = Ingredient.all.reject {|ingredient| @ingredients_in_stock.include?(ingredient) || @grocery_list.include?(ingredient)}
    @user = current_user
    @pantry_item = PantryItem.new(user_id: @user.id)

    if params[:ingredient_name]
      @ingredients_in_stock = @ingredients_in_stock.select {|ingredient| ingredient.name.downcase.include?(params[:ingredient_name].downcase)}
      @grocery_list = @grocery_list.select {|ingredient| ingredient.name.downcase.include?(params[:ingredient_name].downcase)}
      @other_ingredients = @other_ingredients.select {|ingredient| ingredient.name.downcase.include?(params[:ingredient_name].downcase)}
    end

  end


  def show
    @ingredient = Ingredient.find(params[:id])
  end

end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<%= form_tag ingredients_path, method: :get do %>
  <b><%= label_tag :ingredient_name, "Search by ingredient name:" %></b>
  <br>
  <%= search_field_tag :ingredient_name %>
  <%= submit_tag 'Search' %>
<% end %>

<h3>Currently in stock:</h3>
  <% if @ingredients_in_stock.empty? %>
    <p> It looks like you're out of just about everything! Time to make a grocery list and pick a few things up.</p>
  <% else  %>
    <% @ingredients_in_stock.each do |ingredient| %>
    <div class="container">
      <div style ='float: left; padding: 5px;'>
        <%= link_to ingredient.name.titleize, ingredient_path(ingredient)%>
      </div>
        <div style ='float: left; padding: 5px;'>
          <%= form_for (ingredient.to_pantry_item(@user.id) || @pantry_item) do |f|%>
          <%= f.number_field :user_id, type: :hidden %>
          <%= f.number_field :ingredient_id, value: "#{ingredient.id}", type: :hidden %>
          <%= f.text_field :in_stock, value: false, type: :hidden %>
          <%= text_field_tag :source, nil, value: "ingredients_path", type: :hidden%>
          <%= f.submit "Out of Stock, Add to Grocery List"%>
          <% end %>
        </div>
      </div>
      <% end %>
  <% end %>
<br>
<h3>Grocery list:</h3>
<% if @grocery_list.empty? %>
  <p> Grocery list is currently blank.</p>
<% else  %>
<% @grocery_list.each do |ingredient| %>
    <div class="container">
      <div style ='float: left; padding: 5px;'>
    <%= link_to ingredient.name.titleize, ingredient_path(ingredient)%>
    </div>
      <div style ='float: left; padding: 5px;'>
      <%= form_for (ingredient.to_pantry_item(@user.id) || @pantry_item) do |f|%>
      <%= f.number_field :user_id, type: :hidden %>
      <%= f.number_field :ingredient_id, value: "#{ingredient.id}", type: :hidden %>
      <%= f.text_field :in_stock, value: true, type: :hidden %>
      <%= text_field_tag :source, nil, value: "ingredients_path", type: :hidden%>
      <%= f.submit "Buy Ingredient"%>
      <% end %>
    </div>
  </div>
    <% end %>
  <%= form_tag "/pantry_items/groceries" do %>
  <%= text_field_tag :source, nil, value: "ingredients_path", type: :hidden%>
  <%= submit_tag "Buy All Groceries" %>
  <% end %>
<% end %>
<br>

<h3>Other available ingredients:</h3>
  <% if @other_ingredients.empty? %>
    <p> As odd as it sounds, you currently have all available ingredients in your pantry. Can you believe that? Well done! Now, to get cooking....</p>
  <% else  %>
  <% @other_ingredients.each do |ingredient| %>
    <div class="container">
    <div style ='float: left; padding: 5px;'>
      <%= link_to "#{ingredient.name.titleize}", ingredient_path(ingredient) %>
    </div>
    <div style ='float: left; padding: 5px;'>
      <%= form_for (ingredient.to_pantry_item(@user.id) || @pantry_item) do |f|%>
      <%= f.number_field :user_id, type: :hidden %>
      <%= f.number_field :ingredient_id, value: "#{ingredient.id}", type: :hidden %>
      <%= f.text_field :in_stock, value: true, type: :hidden %>
      <%= text_field_tag :source, nil, value: "ingredients_path", type: :hidden%>
      <%= f.submit "Add to Pantry"%>
      <% end %>
    </div>
    <div style ='float: left; padding: 5px;'>
      <%= form_for (ingredient.to_pantry_item(@user.id) || @pantry_item) do |f|%>
      <%= f.number_field :user_id, type: :hidden %>
      <%= f.number_field :ingredient_id, value: "#{ingredient.id}", type: :hidden %>
      <%= f.text_field :in_stock, value: false, type: :hidden %>
      <%= text_field_tag :source, nil, value: "ingredients_path", type: :hidden%>
      <%= f.submit "Add to Grocery List"%>
      <% end %>
    </div>
  </div>
    <% end %>
  </ul>
<% end %>

app/views/ingredients/show.html.erb
<h1><%=@ingredient.name.titleize%></h1>

<h2>Available Recipes:</h2>
<ul>
  <% @ingredient.recipes.each do |recipe|  %>
  <li><%= link_to recipe.name, recipe_path(recipe) %></li>
  <% end %>
</ul>